name: venv
channels:
  - nvidia/label/cuda-12.3.0
  - pytorch-nightly
  - defaults
dependencies:
  - cuda
  - opencv
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - ultralytics==8.1.0
      - supervision==0.2.1
      - PyAudio==0.2.14
      - pynput==1.7.6
      - py-midi==2.0.1
      - pyartnet==1.0.1
